language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      go: 1.5.4
    - os: linux
      dist: trusty
      go: 1.6.2
    - os: linux
      dist: trusty
      go: 1.7
    - os: osx
      go: 1.7

    # This builder does the PPA upload (and nothing else).
    - os: linux
      dist: trusty
      go: 1.7
      env: PPA
      addons:
        apt:
          packages:
            - devscripts
            - debhelper
            - dput
      script:
        - go run build/ci.go debsrc -signer "Felix Lange (Geth CI Testing Key) <fjl@twurst.com>" -upload ppa:lp-fjl/geth-ci-testing

install:
  - go get golang.org/x/tools/cmd/cover
  - wget -q https://github.com/jpmorganchase/constellation/releases/download/v0.0.1-alpha/ubuntu1604.zip -O /tmp/ubuntu1604.zip
  - unzip -d /tmp /tmp/ubuntu1604.zip
  - cp /tmp/ubuntu1604/constellation-node /usr/local/bin && chmod 0755 /usr/local/bin/constellation-node
  - cp /tmp/ubuntu1604/constellation-enclave-keygen /usr/local/bin && chmod 0755 /usr/local/bin/constellation-enclave-keygen
script:
  - go run build/ci.go install
  - go run build/ci.go test -coverage -vet
after_success:
  # - go run build/ci.go archive -type tar

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e09ccdce1048c5e03445
    on_success: change
    on_failure: always
